### ISSUE TITLE
Sparse Convolutional Pretraining

### ISSUE THREAD

**Issue by mileseverett** [arawxx/FSDP-Distributed-Training-of-ConvNextV2-on-CIFAR10#1]
Hello

I don't see the MAE pretrainign the the ConvNextv2 uses in this repo?

Thanks
Miles

**Comment by arawxx** [comment]
Hello there,

No this is not the ConvNextV2 exact paper implementation, I am using the
model to showcase the way we train a model using FSDP, and it's simply
getting trained on CIFAR10.

Here's the link to the actual paper implementation of the model, by Meta:
https://github.com/facebookresearch/ConvNeXt-V2

Best wishes
